version: '3'
services:
  web:
    image: 'diamondyuan/vanaheim'
    restart: always
    ports:
      - '9999:8000'
      - '9998:7001'
    environment:
      MONGODB_URL: mongodb://mongo:27017/admin
  mongo:
    image: 'mongo:latest'
